config/routes.rb
Rails.application.routes.draw do
  root 'currencies#index'

  resources :trips

  resources :countries, only: [:index]

  resources :currencies, only: [:index, :show]

  resources :visited_countries do
      member do
        get 'visit'
        get 'unvisit'
      end
    end

  devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/countries_currencies.rb
class CountriesCurrencies < ActiveRecord::Base
  self.table_name = :countries_currencies
  belongs_to :currency
  belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_and_belongs_to_many :currencies

  def visited_for currency
    elem = VisitedCountry.find_by_currency_id_and_country_id(currency.id, self.id)
    elem.visited
  end

  def visit
    cur_list = VisitedCountry.where(:country_id => self.id)
    cur_list.each do |cur|
      cur.update_attribute(:visited, true)
    end
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_and_belongs_to_many :countries

  def unvisited_countries_count
    VisitedCountry.where(:currency_id => self.id, :visited => false).count
  end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :country
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.admin
  end
end

app/models/visited_country.rb
class VisitedCountry < ActiveRecord::Base
  belongs_to :currencies
  belongs_to :country

  def self.visited_countries_count
    self.select(:country_id).where(:visited => true).map(&:country_id).uniq.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]
  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :code)
    end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
    @countries = @currency.countries
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:name)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
    @visited_countries_count = VisitedCountry.visited_countries_count
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @countries = Country.where(:id => @trip.country_ids.split(" "))
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)
    @trip.country_ids = params[:countries].keys.join(" ")
    params[:countries].keys.each do |country_id|
      country = Country.find(country_id)
      country.visit
    end

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:country_id, :description, :t_date)
    end
end

app/controllers/visited_countries_controller.rb
class VisitedCountriesController < ApplicationController
  before_action :set_country, only: [:visit, :unvisit]
  before_action :authenticate_user!
  # make collected currency in one country, and country visited with this currency
  def visit
    puts params
    elem = VisitedCountry.find_by_country_id_and_currency_id(@country.id, @currency.id)
    elem.visited = true
    elem.save
    redirect_to currency_path(@currency)
  end

  # make uncollected currency in one country, and country unvisited with this currency
  def unvisit
    elem = VisitedCountry.find_by_country_id_and_currency_id(@country.id, @currency.id)
    elem.visited = false
    elem.save
    redirect_to currency_path(@currency)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:country_id])
      @currency = Country.find(params[:currency_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visited_country_params
      params.require(:visited_country).permit(:country_id, :currency_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/countries/index.html.erb
<h1>Listing countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.code %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<%= link_to 'all', "#", :onclick => "$('.disactive').show(); return false" %> | <%= link_to 'active', "#", :onclick => "$('.disactive').hide(); return false" %>

<table>
  <thead>
    <tr>
      <th>( all / unvisited)</th>
      <th>Name</th>
      <th>Code</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <%- unvisited_count = currency.unvisited_countries_count %>
      <tr class="<%= unvisited_count > 0 ? 'active' : 'disactive'%>">
        <td><%= ["(", currency.countries.count, "/", unvisited_count, ")"].join(' ') %></td>
        <td><%= link_to currency.name, currency %></td>
        <td><%= currency.code %></td>
        <td><%= link_to 'Show', currency %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Currency name:</strong>
  <%= @currency.name %>
</p>

<p>
  <strong>Countries:</strong>
  <br/>
  <%- @countries.each do |country|%>
    <%- flag = country.visited_for(@currency)%>
    <table>
      <tr>
        <th> Is visited </th>
        <th> Country name </th>
        <% if can? :manage, @currency %>
          <th> Actions </th>
        <% end %>
      </tr>
      <tr>
        <td>
          <span style='color:<%= flag ? "#01DF74" : "#DF0101" %>'>
            <%= flag ? "visited".html_safe() : "free to go"%>
          </span></td>
        <td>
          <%= country.name %></td>
        <td>
          <% if can? :manage, @currency %>
            <%= flag ? 
    link_to("unvisit", unvisit_visited_country_path(:country_id => country.id, :currency_id => @currency.id)):
    link_to("visit", visit_visited_country_path(:country_id => country.id, :currency_id => @currency.id))%> 
          <% end %>
        </td>
    </table>
    <br/>
  <%end%>
</p>

<%= link_to 'Back', currencies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CurrencyCollection</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
Menu: 
<%= link_to "Currencies" ,currencies_path%>
<%= link_to "Trips" ,trips_path%>
<%= link_to "Countries" ,countries_path%>

<div style="float:right">
  <% if current_user%>
    <%= link_to 'logout', destroy_user_session_path, :method => :delete%>
  <% else %>
    <%= link_to 'login', new_user_session_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :trip_date %><br>
    <%= f.date_select :t_date %>
  </div>

  <% if @trip.new_record?%>
    <%- Country.all.each do|country| %>
    <div class="field" style="float:left; width:30%">
      <label> <%= country.name %></label>
      <input id='countries[<%=country.id %>]' name='countries[<%= country.id %>]' type='checkbox'>
    </div>
    <% end %>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<p>
  <span>
    Visited countries: <%= @visited_countries_count%>
<br/>
<% if can? :create, Trip %>
  <%= link_to 'New Trip', new_trip_path %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Trip date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.description %></td>
        <td><%= trip.t_date %></td>
        <td><%= link_to 'Show', trip %></td>
        <% if can? :manage, trip %>
          <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
          <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @trip.description %>
</p>

<p>
  <strong>Trip date:</strong>
  <%= @trip.t_date %>
</p>

<p>
  <strong>Countries:</strong>
  <% @countries.each do |country| %>
    <br/>
    <span> <%= country.name %> </span>
  <% end %>
</p>
<% if can? :manage, @trip %>
  <%= link_to 'Edit', edit_trip_path(@trip) %> |
<% end %>
<%= link_to 'Back', trips_path %>